PlayMore-V2.0/Models/Booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMore_V5._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int BookId { get; set; }
        public string BookedBy_Userid { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        [Display(Name = "First name")]
        public string BookFName { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name")]
        [Display(Name = "Last name")]
        public string BookLName { get; set; }

        [Required(ErrorMessage = "Please Enter Age")]
        [Display(Name = "Age")]
        public string BookAge { get; set; }
        public int WorkshopWorkshopId { get; set; }
    
        public virtual Workshop Workshop { get; set; }
    }
}

PlayMore-V2.0/Models/SendEmailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using System.Linq;
using System.Web;

namespace PlayMore_V5._0.Models
{
    public class SendEmailViewModel
    {
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "Please enter an email address.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string ToEmail { get; set; }

        [Required(ErrorMessage = "Please enter a subject.")]
        public string Subject { get; set; }

       

        [Required(ErrorMessage = "Please enter the contents")]
        public string Contents { get; set; }

        public HttpPostedFileBase Upload { get; set; }




    }
}

PlayMore-V2.0/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PlayMore_V5._0.Models;
using PlayMore_V5._0.Util;

namespace PlayMore_V5._0.Controllers
{
    public class BookingsController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Bookings
        [Authorize]
        public ActionResult Index()
        {

            var userID = User.Identity.GetUserId();
            var book = db.Bookings.Where(b => b.BookedBy_Userid == userID).ToList();
            //var bookings = db.Bookings.Include(b => b.Workshop);

            //Selecting only bookings of future
            var futureBook = new List<Booking>();
            foreach(Booking b in book)
            {
                if(DateTime.Compare(b.Workshop.WorkshopDate, DateTime.Now) > 0)
                {
                    futureBook.Add(b);
                }
            }

            if (User.IsInRole("admin"))
            {
                var b = db.Bookings.Include(k=>k.Workshop.Game);
                book = db.Bookings.ToList();
                foreach (Booking b2 in book)
                {
                    if (DateTime.Compare(b2.Workshop.WorkshopDate, DateTime.Now) > 0)
                    {
                        futureBook.Add(b2);
                    }
                }
            }

            return View(futureBook);
        }
        [Authorize(Roles = "user")]
        public ActionResult UserWSList()
        {
            var userID = User.Identity.GetUserId();
            var book = db.Bookings.Where(b => b.BookedBy_Userid == userID).ToList();
            //var workshops1 = db.Workshops.Include(w => w.Game).Include(w => w.Coach);

            var workshops1 = db.Workshops.Include(w => w.Coach).Include(w => w.Game).ToList();
            var ActiveWorkshops = new List<Workshop>();
            foreach (Workshop w in workshops1)
            {
                if (DateTime.Compare(w.WorkshopDate, DateTime.Now) > 0)
                {
                    ActiveWorkshops.Add(w);
                }
            }



            return View(ActiveWorkshops);
        }

        [Authorize(Roles = "user")]
        public ActionResult UserConfirmBook(int? id)
        {
            var ws = db.Workshops.Find(id);

            Booking b = new Booking();
            b.BookedBy_Userid = User.Identity.GetUserId();

            b.WorkshopWorkshopId = ws.WorkshopId;


            ViewBag.WSLocation = ws.WorkshopLocation;
            ViewBag.WSDate = ws.WorkshopDate;



            return View(b);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user")]
        public ActionResult UserConfirmBook([Bind(Include = "BookFName,BookLName,BookAge,WorkshopWorkshopId")] Booking booking)
        {
            booking.BookedBy_Userid = User.Identity.GetUserId();

            //Check for existing booking if any
            var selectedWS = db.Workshops.Where(w=>w.WorkshopId== booking.WorkshopWorkshopId).ToList();

            var allBooks = db.Bookings.ToList();


            foreach(Booking bookDB in allBooks) {

                if(bookDB.BookedBy_Userid == booking.BookedBy_Userid) { 
                    if(booking.WorkshopWorkshopId == bookDB.WorkshopWorkshopId && booking.BookFName == bookDB.BookFName 
                            && booking.BookLName == bookDB.BookLName && booking.BookAge == bookDB.BookAge)
                    {
                        ViewBag.errorMsg = "Already booked for the same workshop !!!";
                        return View();
                    }
                    else if(selectedWS[0].WorkshopDate == bookDB.Workshop.WorkshopDate && booking.BookFName == bookDB.BookFName
                            && booking.BookLName == bookDB.BookLName && booking.BookAge == bookDB.BookAge)
                    {
                        ViewBag.errorMsg = "Already booked for a workshop same day !!!";
                        return View();
                    }
                }
            }

            //End of checking


            //Check for number of bookings present for the particular user
            var bookingsForUser = db.Bookings.Where(b => b.BookedBy_Userid == booking.BookedBy_Userid).ToList();
            var futureBook = new List<Booking>();
            foreach (Booking b in bookingsForUser)
            {
                if (DateTime.Compare(b.Workshop.WorkshopDate, DateTime.Now) > 0)
                {
                    futureBook.Add(b);
                }
            }

            if (futureBook.Count >= AppConstants.MaximumBookings)
            {
                ViewBag.errorMsg = "User can only book a maximum of "+AppConstants.MaximumBookings+" bookings";
                return View();
            }



            //If no booking present then saving in DB

            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();


                //On success save, sending confirmation email to user
                String toEmail = User.Identity.Name ;
                String subject = "Playmore booking confirmation";

                //Making content (Mail body) for booking confirmation
                String content = "";
                content += "<p>Booking confirmed.</p><br / > <p>Booking details are as follows:</p>";

                content += "<table border='1'><tr><th>Workshop Date:</th><td>" + selectedWS[0].WorkshopDate + "</td></tr>"
                            + "<tr><th>First Name :</th><td>" + booking.BookFName + "</td></tr>"
                            + "<tr><th>Last Name :</th><td>" + booking.BookLName + "</td></tr>"
                            + "<tr><th>Game :</th><td>" + selectedWS[0].Game.GameName + "</td></tr>"
                            + "<tr><th>WorkShop Location :</th><td>" + selectedWS[0].WorkshopLocation + "</td></tr>"
                            + "<tr><th>WorkShop Fees :</th><td>" + selectedWS[0].WorkShopFees + "</td></tr>";

                content += "</table>";

                EmailSender es = new EmailSender();
                es.Send(toEmail, subject, content, null);


                return RedirectToAction("CreateFeedback");
                //return RedirectToAction("Index");
            }


            return View();
        }

        public ActionResult CreateFeedback()
        {
            return View();
        }

        public ActionResult SetRating(int? id)
        {
            var rating = id;

            var UserName = User.Identity.Name;
            var NewRating = new Rating();
            NewRating.RatingGiven = (int)rating;
            NewRating.UserName = UserName;

            db.Ratings.Add(NewRating);
            db.SaveChanges();

            return RedirectToAction("Index");


        }

            // GET: Bookings/Details/5
            public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.WorkshopWorkshopId = new SelectList(db.Workshops, "WorkshopId", "WorkshopLocation");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "BookId,BookedBy_Userid,BookFName,BookLName,BookAge,WorkshopWorkshopId")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.WorkshopWorkshopId = new SelectList(db.Workshops, "WorkshopId", "WorkshopLocation", booking.WorkshopWorkshopId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.WorkshopWorkshopId = new SelectList(db.Workshops, "WorkshopId", "WorkshopLocation", booking.WorkshopWorkshopId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "BookId,BookedBy_Userid,BookFName,BookLName,BookAge,WorkshopWorkshopId")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();

                ViewBag.WorkshopWorkshopId = new SelectList(db.Workshops, "WorkshopId", "WorkshopLocation", booking.WorkshopWorkshopId);
                ViewBag.editMsg = "Booking details edited successfully !!";
                return View(booking);


                //return RedirectToAction("Index");

PlayMore-V2.0/Views/Bookings/Charts.cshtml
@{
   ViewBag.Title = "ChartView";
}
 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Chart View</title>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"> </script>



    <!--<link href="~/Content/styleSheet.css" rel="stylesheet" /> -->



    <script type="text/javascript">

        //Charts
        function exportFile() {
            window.print();
        }




        function onAllClick() {
            document.getElementById("chartContainer1").style.display = "inline-block";
            document.getElementById("chartContainer2").style.display = "inline-block";
            document.getElementById("chartContainer3").style.display = "inline-block";
            document.getElementById("chartContainer4").style.display = "inline-block";
        }
        function onBarClick() {
            document.getElementById("Bargraph").style.backgroundColor = "red";

            document.getElementById("chartContainer1").style.display = "inline-block";
            document.getElementById("chartContainer2").style.display = "None";
            document.getElementById("chartContainer3").style.display = "None";
            document.getElementById("chartContainer4").style.display = "None";

        }

        function onPieClick() {
            document.getElementById("chartContainer1").style.display = "None";
            document.getElementById("chartContainer2").style.display = "inline-block";
            document.getElementById("chartContainer3").style.display = "None";
            document.getElementById("chartContainer4").style.display = "None";
        }

        function onLineClick() {
            document.getElementById("chartContainer1").style.display = "None";
            document.getElementById("chartContainer2").style.display = "None";
            document.getElementById("chartContainer3").style.display = "inline-block";
            document.getElementById("chartContainer4").style.display = "None";
        }

        function onAreaClick() {
            document.getElementById("chartContainer1").style.display = "None";
            document.getElementById("chartContainer2").style.display = "None";
            document.getElementById("chartContainer3").style.display = "None";
            document.getElementById("chartContainer4").style.display = "Inline";
        }



    </script>


    <script type="text/javascript">

       window.onload = function () {

           var result = @Html.Raw(ViewBag.DataPoints);
            var dataPoints =[];
           for (var i = 0; i < result.length; i++){

               dataPoints.push({ label: result[i].Label, x: result[i].X, y: result[i].Y });

            }


         var chart1 = new CanvasJS.Chart("chartContainer1", {
            theme: "theme2",
            animationEnabled: true,
            title: {
               text: ""
            },

            data: [
               {
                  // change type to bar, line, area, pie, etc.
                  type: "bar",
                    dataPoints: dataPoints

               }
            ]
         });


           var chart2 = new CanvasJS.Chart("chartContainer2", {
               theme: "theme2",
               animationEnabled: true,
               title: {
                   text: ""
               },
               data: [
                   {
                       // change type to bar, line, area, pie, etc.
                       type: "pie",
                       dataPoints: dataPoints

                   }
               ]
           });


           var chart3 = new CanvasJS.Chart("chartContainer3", {
               theme: "theme2",
               animationEnabled: true,
               title: {
                   text: ""
               },
               data: [
                   {
                       // change type to bar, line, area, pie, etc.
                       type: "line",
                       dataPoints: dataPoints

                   }
               ]
           });

           var chart4 = new CanvasJS.Chart("chartContainer4", {
               theme: "theme2",
               animationEnabled: true,
               title: {
                   text: ""
               },
               data: [
                   {
                       // change type to bar, line, area, pie, etc.
                       type: "area",
                       dataPoints: dataPoints

                   }
               ]
           });


           chart1.render();
           chart2.render();
           chart3.render();
           chart4.render();


      };
    </script>
</head>


<body>

    <h2>Number of Bookings per game</h2>

<br />
<div>
    <input type="button" class="button" id="Allgraph" value="All Graph" onclick="javascript:onAllClick()" />
    <input type="button" class="button" id="Bargraph" value="Bar Graph" onclick="javascript:onBarClick()" />
    <input type="button" class="button" id="Piegraph" value="Pie Graph" onclick="javascript:onPieClick()" />
    <input type="button" class="button" id="Linegraph" value="Line Graph" onclick="javascript:onLineClick()" />
    <input type="button" class="button" id="Areagraph" value="Area Graph" onclick="javascript:onAreaClick()" />

    <div style="float: right;">
        <input type="button" class="button" id="ExportPDF" value="Export Charts" onclick="javascript:exportFile()" />
        <input type="button" class="button" id="Bargraph" value="Email Chart" onclick="location.href='@Url.Action("Send_Email", "Bookings")'" />
    </div>
</div>

    <div style="float: right;">
        
    </div>



    <br />

    <p>
        <div id="chartContainer1" style="width: 45%; height: 300px;display: inline-block;"></div>
        <div id="chartContainer2" style="width: 45%; height: 300px;display: inline-block;"></div><br /><br />
        <div id="chartContainer3" style="width: 45%; height: 300px;display: inline-block;"></div>
        <div id="chartContainer4" style="width: 45%; height: 300px;display: inline-block;"></div>


    </p>



</body>
</html>

PlayMore-V2.0/Views/Bookings/Create.cshtml
@model PlayMore_V5._0.Models.Booking

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Booking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookedBy_Userid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookedBy_Userid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookedBy_Userid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookFName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookFName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookFName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookLName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookLName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookLName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopWorkshopId, "WorkshopWorkshopId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WorkshopWorkshopId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkshopWorkshopId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlayMore-V2.0/Views/Bookings/CreateFeedback.cshtml
@{
    ViewBag.Title = "CreateFeedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        .rating {
            unicode-bidi: bidi-override;
            direction: rtl;
        }

            .rating > span {
                display: inline-block;
                position: relative;
                width: 2em;
            }

                .rating > span:hover:before,
                .rating > span:hover ~ span:before {
                    content: "\2605";
                    position: absolute;
                }
    </style>
</head>
<h3>Make Booking</h3>
<div>
    <p class="success">Booking made succesfully !!!</p>
</div>


<script>
    function clickPop(val) {
        window.location.href = '@Url.Action("SetRating", "Bookings")/' + val;
    }
</script>
<br />

<br />

<p>Please Rate your booking Experience</p>
<h2>
    <div class="rating" style="float: left;">

        <span onclick="javascript:clickPop('5')">☆</span>
        <span onclick="javascript:clickPop('4')">☆</span>
        <span onclick="javascript:clickPop('3')">☆</span>
        <span onclick="javascript:clickPop('2')">☆</span>
        <span onclick="javascript:clickPop('1')">☆</span>

    </div>
</h2>


<br />

<br />

<br />

<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<br />

PlayMore-V2.0/Views/Bookings/Delete.cshtml
@model PlayMore_V5._0.Models.Booking

@{
    ViewBag.Title = "Delete";
}

<h2>CancelBooking</h2>

<h3>Are you sure you want to Cancel the booking?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        @*  <dt>
                @Html.DisplayNameFor(model => model.BookedBy_Userid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BookedBy_Userid)
            </dd>
        *@
        <dt>
            @Html.DisplayNameFor(model => model.BookFName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookFName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookLName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookLName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Workshop.WorkshopLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workshop.WorkshopLocation)
        </dd>

    </dl>
    <br />
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">

    @Html.ActionLink("Back to List", "Index") |
    <input type="submit" value="Cancel" class="btn btn-default" id="myDelete" /> 
</div>
    }
</div>

<script src="~/Scripts/notify.min.js"></script>

<script>
    $('#myDelete').click(function () {
        $.notify("Item deleted!", { type: "info", delay: 10000, align: "center", verticalAlign: "top", animation: true, icon: "check", blur: 0.2 });
    });
</script>

PlayMore-V2.0/Views/Bookings/DeleteFeedback.cshtml
@{
    ViewBag.Title = "DeleteFeedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cancel Booking</h2>

<div><p class="success">
        Booking has been cancelled !!
    </p></div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PlayMore-V2.0/Views/Bookings/Index.cshtml
@model IEnumerable<PlayMore_V5._0.Models.Booking>

@{
    ViewBag.Title = "Index";
}

<h2>Bookngs</h2>

<script>

    function printPage1() {
        window.print();
    }

    function printPage2() {
        window.printPage();
    }
</script>



<p>
    <div>
        @if (User.IsInRole("admin"))
        {
            @Html.ActionLink("Create New", "Create")
        }
        @* <div style="float: right;">
            <input type="button" class="button" value="View Charts"
                   onclick="location.href='@Url.Action("Charts", "Bookings")'" />
        </div>
        *@
    </div>
</p>

<br />



<br />

<table class="table">
    <thead>
        <tr>
            @*
                <th>
                    @Html.DisplayNameFor(model => model.BookedBy_Userid)
                </th>
            *@
            <th>
                @Html.DisplayNameFor(model => model.BookFName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookLName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookAge)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Workshop.WorkshopDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Workshop.WorkShopFees)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Workshop.WorkshopLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Workshop.Game.GameName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                @*
                    <td>
                        @Html.DisplayFor(modelItem => item.BookedBy_Userid)
                    </td>
                *@
                <td>
                    @Html.DisplayFor(modelItem => item.BookFName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookLName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookAge)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Workshop.WorkshopDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Workshop.WorkShopFees)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Workshop.WorkshopLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Workshop.Game.GameName)
                </td>


                <td>

                    @if (User.IsInRole("admin"))
                    {

                        @Html.ActionLink("Edit", "Edit", new { id = item.BookId })

                    }

                    | @Html.ActionLink("Details", "Details", new { id = item.BookId })


                    |@Html.ActionLink("Cancel", "Delete", new { id = item.BookId })


                </td>



            </tr>
        }
    </tbody>
</table>




@section Scripts {
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.js")
    @Scripts.Render("~/Scripts/DataTables/dataTables.bootstrap.js")

    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });
    </script>
}
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css"
      rel="stylesheet" />

PlayMore-V2.0/Views/Bookings/Send_Email.cshtml
@model PlayMore_V5._0.Models.SendEmailViewModel

@{
    ViewBag.Title = "Send Email";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Send Email</h2>


@using (Html.BeginForm("Send_Email", "Bookings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    if (@ViewBag.Result != null)
    {
        <div>
            <p class="success">  @ViewBag.Result </p>

        </div>
    }



    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ToEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>



        <div>

            @Html.TextBoxFor(model => model.Upload, new { type = "file" })
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send Mail" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Charts", "Charts")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}