PlayMore-V2.0/Models/Workshop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMore_V5._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshop()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int WorkshopId { get; set; }
        public System.DateTime WorkshopDate { get; set; }

        [Required(ErrorMessage = "Please Enter location")]
        [Display(Name = "Workshop Location")]
        public string WorkshopLocation { get; set; }

        [Required(ErrorMessage = "Please Enter location lattitude")]
        [Display(Name = "Lattitude of location")]
        public string WSLocLattitude { get; set; }

        [Required(ErrorMessage = "Please Enter location longitude")]
        [Display(Name = "Longitude of location")]
        public string WSLocLongitude { get; set; }

        [Required(ErrorMessage = "Please Enter Workshop fees")]
        [Display(Name = "Fees of workshop")]
        [RegularExpression(@"^\$?\d+(\.(\d{2}))?$", ErrorMessage ="Enter only numbers for Price")]
        public string WorkShopFees { get; set; }

        [Display(Name = "Coach Name")]
        public int CoachCoachId { get; set; }

        [Display(Name ="Game Name")]
        public int GameGameId { get; set; }
    
        public virtual Coach Coach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Game Game { get; set; }
    }
}

PlayMore-V2.0/Controllers/WorkshopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using PlayMore_V5._0.Models;
using PlayMore_V5._0.Util;

namespace PlayMore_V5._0.Controllers
{
    [Authorize(Roles = "admin")]
    public class WorkshopsController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Workshops
        public ActionResult Index()
        {

            var workshops = db.Workshops.Include(w => w.Coach).Include(w => w.Game).ToList();
            var ActiveWorkshops = new List<Workshop>();
            foreach(Workshop w in workshops)
            {
                if(DateTime.Compare(w.WorkshopDate, DateTime.Now ) > 0)
                {
                    ActiveWorkshops.Add(w);
                }
            }

            return View(ActiveWorkshops);
        }

        // GET: Workshops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workshop workshop = db.Workshops.Find(id);
            if (workshop == null)
            {
                return HttpNotFound();
            }
            return View(workshop);
        }

        // GET: Workshops/Create
        public ActionResult Create()
        {
            ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName");
            ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName");
            return View();
        }

        // POST: Workshops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorkshopId,WorkshopDate,WorkshopLocation,WSLocLattitude,WSLocLongitude,WorkShopFees,CoachCoachId,GameGameId")] Workshop workshop)
        {


            //Setting workshop time as 10am
            var WorkDate = workshop.WorkshopDate;
            TimeSpan ts = new TimeSpan(10, 0, 0);
            WorkDate = WorkDate.Date + ts;
            workshop.WorkshopDate = WorkDate;

            //To check if selected coach is of the game
            var SelectedCoach = db.Coaches.Find(workshop.CoachCoachId);
            
            if( SelectedCoach.GameGameId != workshop.GameGameId)
            {
                ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName");
                ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName");
                ViewBag.errormsg = "Selected Coach doesnot train " + db.Games.Find(workshop.GameGameId).GameName+ ". Please change coach !";
                return View();
            }


            if (ModelState.IsValid)
            {
                db.Workshops.Add(workshop);
                db.SaveChanges();
                return RedirectToAction("CreateFeedback");
                // return RedirectToAction("Index");
            }

            ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName", workshop.CoachCoachId);
            ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName", workshop.GameGameId);
            return View(workshop);
        }

        public ActionResult CreateFeedback()
        {
            return View();
        }


        // GET: Workshops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workshop workshop = db.Workshops.Find(id);
            if (workshop == null)
            {
                return HttpNotFound();
            }
            ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName", workshop.CoachCoachId);
            ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName", workshop.GameGameId);
            return View(workshop);
        }

        // POST: Workshops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkshopId,WorkshopDate,WorkshopLocation,WSLocLattitude,WSLocLongitude,WorkShopFees,CoachCoachId,GameGameId")] Workshop workshop)
        {
            //Setting workshop time as 10am
            var WorkDate = workshop.WorkshopDate;
            TimeSpan ts = new TimeSpan(10, 0, 0);
            WorkDate = WorkDate.Date + ts;
            workshop.WorkshopDate = WorkDate;


            if (ModelState.IsValid)
            {
                db.Entry(workshop).State = EntityState.Modified;
                db.SaveChanges();

                ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName", workshop.CoachCoachId);
                ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName", workshop.GameGameId);
                ViewBag.editmsg = "Workshop Details edited successfully !!!";
                return View(workshop);

               // return RedirectToAction("Index");
            }
            ViewBag.CoachCoachId = new SelectList(db.Coaches, "CoachId", "CoachFName", workshop.CoachCoachId);
            ViewBag.GameGameId = new SelectList(db.Games, "GameId", "GameName", workshop.GameGameId);
            return View(workshop);
        }

        // GET: Workshops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workshop workshop = db.Workshops.Find(id);
            if (workshop == null)
            {
                return HttpNotFound();
            }
            return View(workshop);
        }

        // POST: Workshops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Workshop workshop = db.Workshops.Find(id);

            //Check if bookings are present for the workshop

            var bookings = db.Bookings.Where(b => b.WorkshopWorkshopId == id).ToList();

            if (bookings.Count() > 1)
            {
                ViewBag.deleteError = "Bookings present for the Selected Workshop. Delete them to delete the workshop";
                return View(workshop);
            }

            db.Workshops.Remove(workshop);
            db.SaveChanges();

            return RedirectToAction("DeleteFeedback");
            //return RedirectToAction("Index");
        }


        public ActionResult DeleteFeedback()
        {
            return View();
        }

        public ActionResult BoradcastEmail()
        {
            var context = new ApplicationDbContext();
            var userStore = new UserStore<ApplicationUser>(context);
            var list = new List<String>();
            foreach (var u in userStore.Users)
            {
                list.Add(u.Email);
            }
            ViewBag.listEmail = list;

            return View();
        }

        public ActionResult SendBoradcastEmail()
        {
            // var v = User.Identity.Name;
            var context = new ApplicationDbContext();
            var userStore = new UserStore<ApplicationUser>(context);
            var list = new List<String>();
            foreach (var u in userStore.Users)
            {
                list.Add(u.Email);
            }

            List<String> toEmailList = list;
            String subject ="Playmore: Upcoming workshops";

            //Making content
            var Workshops = db.Workshops.ToList();

            String content = "<table border='1'>";
            content = content + "<tr><th>Workshop Date</th><th> Workshop Location</th>" +
                "<th>Workshop Fees</th><th>Game</th>";
            foreach (Workshop w in Workshops)
            {
                content = content + "<tr><td>" + w.WorkshopDate + "</td><td>" + w.WorkshopLocation + "</td><td>" 
                    + w.WorkShopFees + "</td><td>" +
                    w.Game.GameName + "</td>" ;
            }
            content = content + "<table>";


            EmailSender es = new EmailSender();
            es.SendBroadcast(toEmailList, subject, content);


            return RedirectToAction("Index");
        }

        public ActionResult BoradcastEmailSuccess()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlayMore-V2.0/Views/Workshops/BoradcastEmail.cshtml
@{
    ViewBag.Title = "BoradcastEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />

<h3>BoradcastEmail</h3>
<br />
<p>
    Click to send the upcoming workshop details to all registered users :

    <input type="button" class="button" id="Bargraph" value="Send Broadcast Email"
           onclick="location.href='@Url.Action("SendBoradcastEmail", "Workshops")'" />
</p>

<br />
    @foreach (var str in ViewBag.listEmail)
    {
        <ul>@Html.Raw(str); </ul>
    }

PlayMore-V2.0/Views/Workshops/BoradcastEmailSuccess.cshtml
@{
    ViewBag.Title = "BoradcastEmailSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Broadcast Email</h2>

<p class="success"> Email has send successfully !!!</p>

<br />
<br />
<br />
<br />

<div>
    @Html.ActionLink("List Workshops", "Index")
</div>

PlayMore-V2.0/Views/Workshops/Create.cshtml
@model PlayMore_V5._0.Models.Workshop

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.date.js"></script>


<script>
    $(function () {
        $('#txtDatePicker').datepicker(
            {
                dateFormat: 'dd/mm/yy',
                changeMonth: true,
                changeYear: true,
                yearRange: '1950:2100',
                defaultDate: '20/08/2020',
                minDate: 0
            });
    });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    if (@ViewBag.errormsg != null)
    {
        <div>
            <p class="error">  @ViewBag.errormsg </p>

        </div>
    }

    <div class="form-horizontal">
        <h4>Workshop</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })





        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkshopDate, new { htmlAttributes = new { @class = "form-control", @id = "txtDatePicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.WorkshopDate, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkshopLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkshopLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WSLocLattitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WSLocLattitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WSLocLattitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WSLocLongitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WSLocLongitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WSLocLongitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkShopFees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkShopFees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkShopFees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameGameId, "GameGameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameGameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameGameId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CoachCoachId, "CoachCoachId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CoachCoachId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CoachCoachId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlayMore-V2.0/Views/Workshops/CreateFeedback.cshtml
@{
    ViewBag.Title = "CreateFeedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateFeedback</h2>

<p class="success">New Workshop added successfully !!</p>

<div class="form-actions no-color">
    @Html.ActionLink("Back to List", "Index")
</div>

PlayMore-V2.0/Views/Workshops/Delete.cshtml
@model PlayMore_V5._0.Models.Workshop

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h4>Are you sure you want to delete this?</h4>
<div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        if (@ViewBag.deleteError != null)
        {
            <div>
                <p class="error">  @ViewBag.deleteError </p>

            </div>
        }


        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.WorkshopDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WorkshopDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WorkshopLocation)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WorkshopLocation)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WSLocLattitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WSLocLattitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WSLocLongitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WSLocLongitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WorkShopFees)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WorkShopFees)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Coach.CoachFName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Coach.CoachFName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Game.GameName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Game.GameName)
            </dd>

        </dl>





        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PlayMore-V2.0/Views/Workshops/DeleteFeedback.cshtml
@{
    ViewBag.Title = "DeleteFeedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteFeedback</h2>

<div>
    <p class="success">The selected workshop has been deleted !!</p>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PlayMore-V2.0/Views/Workshops/Details.cshtml
@model PlayMore_V5._0.Models.Workshop

@{
    ViewBag.Title = "Details";
}

<h2>Workshop Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkshopDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkshopDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkshopLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkshopLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WSLocLattitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WSLocLattitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WSLocLongitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WSLocLongitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkShopFees)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkShopFees)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coach.CoachFName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.CoachFName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Game.GameName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.GameName)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.WorkshopId }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

PlayMore-V2.0/Views/Workshops/Edit.cshtml
@model PlayMore_V5._0.Models.Workshop

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.date.js"></script>


<script>
    $(function () {
        $('#txtDatePicker').datepicker(
            {
                dateFormat: 'dd/mm/yy',
                changeMonth: true,
                changeYear: true,
                yearRange: '1950:2100',
                defaultDate: '20/08/2020',
                minDate: 0
            });
    });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    if (@ViewBag.editmsg != null)
    {
        <div>
            <p class="success">  @ViewBag.editmsg </p>

        </div>
    }


    <div class="form-horizontal">
        <h4>Workshop</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WorkshopId)

        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkshopDate, new { htmlAttributes = new { @class = "form-control", @id = "txtDatePicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.WorkshopDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkshopLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkshopLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkshopLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WSLocLattitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WSLocLattitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WSLocLattitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WSLocLongitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WSLocLongitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WSLocLongitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkShopFees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkShopFees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkShopFees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoachCoachId, "CoachCoachId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CoachCoachId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CoachCoachId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameGameId, "GameGameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameGameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameGameId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlayMore-V2.0/Views/Workshops/Index.cshtml
@model IEnumerable<PlayMore_V5._0.Models.Workshop>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<p>
    <div>
        @Html.ActionLink("Create New", "Create")
        <div style="float: right;">
            
            <input type="button" class="button" id="Bargraph" value="Broadcast Email" onclick="location.href='@Url.Action("BoradcastEmail", "Workshops")'" />
        </div>
    </div>

</p>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WorkshopDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkshopLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WSLocLattitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WSLocLongitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkShopFees)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coach.CoachFName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Game.GameName)
            </th>
            <th></th>
        </tr>
    </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkshopDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkshopLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WSLocLattitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WSLocLongitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkShopFees)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Coach.CoachFName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Game.GameName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.WorkshopId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.WorkshopId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.WorkshopId })
                </td>
            </tr>
        }

</table>


@section Scripts {

    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.js")
    @Scripts.Render("~/Scripts/DataTables/dataTables.bootstrap.js")
    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });



    </script>
}
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css"
      rel="stylesheet" />